### ISSUE TITLE
https://github.com/snyk/snyk-visual-studio-plugin/issues

### ISSUE THREAD

**Issue by Rakeshachar** [snyk/snyk-visual-studio-plugin#163]
we have .net core web api project with project.assets.json file and visual studio 2019, and we have followed all the steps to of adding snyk extension, but whenever we run scan the project files are not detected. can you please help us in this regard.

**Comment by aldanchenko** [comment]
If Snyk Code shows  `no supported code available` you could try to check .gitignore and .dcignore file rules. Check if there are any rules that exclude your project's source files. For example, you could try to delete all rules from .dcignore file (just remove content, not file) and try to run a scan again

**Comment by Rakeshachar** [comment]
> 
Thank you as you mentioned I have sent the mail with logs and with more details.

**Comment by Rakeshachar** [comment]
Hello Aleksandr

Thanks for insight, and I have tried removing both  .gitignore and .dcignore file, but still its not processing project files, do i need to set any specific project path ?

Thanks
Rakesh

________________________________

**Comment by Xcaciv** [comment]
I have reproduced this issue by simply checking out https://github.com/srini0x00/dvta and trying to scan it. This is also reproduced by forking importing it via the Snyk SaaS.

**Comment by Rakeshachar** [comment]
Please let me know if any other resolution i can try

**Comment by aldanchenko** [comment]
Hi @Rakeshachar 👋

We created fix for this issue #173. I'll let you know when it will be in Marketplace.

Thank you for patience!

**Comment by aldanchenko** [comment]
Hi @Rakeshachar 👋

We released new version (1.1.20) which should fix this problem. Could you try it, please?

Best regards,
Alex

**Comment by Xcaciv** [comment]
@aldanchenko , I know I am not the reporter of the bug, but I can confirm that the change worked for me.  I updated, and I can now get results and use the results window on the xcaciv/dtva project. (SaaS is still not working)

**Comment by aldanchenko** [comment]
Hi @Xcaciv,

Could you share more details about "Code scans do not work despite it being C#"? You have .NET project and Snyk Code scans not working?

**Comment by Xcaciv** [comment]
@aldanchenko , correct. It can be reproduced with  https://github.com/Xcaciv/dvta . It seemed related to this issue. However, should I open another? Previously it was not finding anything to scan. Now it does SCA, but nothing else across VS, CLI and SaaS.

**Comment by aldanchenko** [comment]
Thank you @Xcaciv! Yes, lets open another issue for it.
